### ISSUE TITLE
No module named reddis

### ISSUE THREAD

**Issue by Jhamali** [PalisadoesFoundation/infosetDB#148]
Bug report

### Input Code

```python

    python3 docker/api.py
```

### Infoset Configuration (etc/config.yaml)

```yaml
{
 main:
  db_file: ./infoset/db/infoset-db.db
  bind_port: 6000
  db_hostname: localhost
  db_name: infoset
  db_password: password
  db_username: root
  ingest_cache_directory: ./cache
  ingest_pool_size: 20
  interval: 60
  listen_address: 0.0.0.0
  log_directory: ./log
  log_level: debug
  log_file: infoset-ng.log
  memcached_hostname: localhost
  memcached_port: 11211
  redis_hostname: localhost
  redis_port: 6379
  sqlalchemy_max_overflow: 10
  sqlalchemy_pool_size: 10
  username: infoset
}
```

### Expected Behavior

API starts

### Current Behavior

```bash
Traceback (most recent call last):
  File "docker/api.py", line 17, in <module>
    from infoset.api import API
  File "/home/jhamali/Desktop/infoset-ng/infoset/api/__init__.py", line 15, in <module>
    from infoset.utils import redis
  File "/home/jhamali/Desktop/infoset-ng/infoset/utils/redis.py", line 2, in <module>
    import redis
ImportError: No module named 'redis'
```
### Context

Trying to start infosetDB for testing another application

### Your Environment

| software         | version(s)
| ---------------- | -------
| infoset          |  2.1.1
| node             | 4.2.6
| npm              | 3.5.2
| Operating System |Ubuntu 16

**Comment by Jhamali** [comment]
Still relevant? @Pr0x1m4

**Comment by Pr0x1m4** [comment]
Nah, we fixed this in the latest version. Closing.
